name: Build V8
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-mac:
    name: mac
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: compile
        run: |
          make macos-${{ matrix.platform }}
          ./spin 1
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/spin
          name: spin-macos-${{ matrix.platform }}

  build-linux:
    name: linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: compile
        run: |
          make linux-${{ matrix.platform }}
          ./spin 1
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/spin
          name: spin-linux-${{ matrix.platform }}
